/**
 * Workflow Generation Chat Store Tests
 *
 * Tests for workflow generation chat panel state management including
 * messages, thinking content, streaming, and workflow plans.
 */

import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";

// Mock crypto.randomUUID for predictable IDs
let uuidCounter = 0;
vi.stubGlobal("crypto", {
    randomUUID: () => `uuid-${++uuidCounter}`
});

import { useWorkflowGenerationChatStore } from "../workflowGenerationChatStore";

// Mock data factories
function createMockWorkflowPlan(overrides?: Record<string, unknown>) {
    const defaults = {
        id: "plan-123",
        name: "Generated Workflow",
        description: "A workflow generated by AI",
        nodes: [
            {
                id: "node-1",
                type: "llm",
                label: "Process Input",
                config: {},
                position: { x: 0, y: 0 }
            }
        ],
        edges: [],
        entryNodeId: "node-1",
        summary: "A workflow that processes input"
    };
    return { ...defaults, ...overrides };
}

// Reset store before each test
function resetStore() {
    uuidCounter = 0;
    useWorkflowGenerationChatStore.setState({
        isPanelOpen: false,
        panelWidth: 500,
        messages: [],
        isStreaming: false,
        isThinking: false,
        currentThinkingContent: "",
        selectedConnectionId: null,
        selectedModel: null,
        enableThinking: true,
        thinkingBudget: 4096,
        currentPlan: null,
        isCreatingWorkflow: false
    });
}

describe("workflowGenerationChatStore", () => {
    beforeEach(() => {
        resetStore();
        vi.clearAllMocks();
    });

    afterEach(() => {
        resetStore();
    });

    // ===== Initial State =====
    describe("initial state", () => {
        it("has correct initial state", () => {
            resetStore();
            const state = useWorkflowGenerationChatStore.getState();

            expect(state.isPanelOpen).toBe(false);
            expect(state.panelWidth).toBe(500);
            expect(state.messages).toEqual([]);
            expect(state.isStreaming).toBe(false);
            expect(state.isThinking).toBe(false);
            expect(state.currentThinkingContent).toBe("");
            expect(state.selectedConnectionId).toBeNull();
            expect(state.selectedModel).toBeNull();
            expect(state.enableThinking).toBe(true);
            expect(state.thinkingBudget).toBe(4096);
            expect(state.currentPlan).toBeNull();
            expect(state.isCreatingWorkflow).toBe(false);
        });
    });

    // ===== Panel State =====
    describe("panel state", () => {
        it("opens panel", () => {
            useWorkflowGenerationChatStore.getState().openPanel();
            expect(useWorkflowGenerationChatStore.getState().isPanelOpen).toBe(true);
        });

        it("closes panel", () => {
            useWorkflowGenerationChatStore.setState({ isPanelOpen: true });
            useWorkflowGenerationChatStore.getState().closePanel();
            expect(useWorkflowGenerationChatStore.getState().isPanelOpen).toBe(false);
        });

        it("toggles panel", () => {
            expect(useWorkflowGenerationChatStore.getState().isPanelOpen).toBe(false);

            useWorkflowGenerationChatStore.getState().togglePanel();
            expect(useWorkflowGenerationChatStore.getState().isPanelOpen).toBe(true);

            useWorkflowGenerationChatStore.getState().togglePanel();
            expect(useWorkflowGenerationChatStore.getState().isPanelOpen).toBe(false);
        });

        it("sets panel width within constraints", () => {
            useWorkflowGenerationChatStore.getState().setPanelWidth(600);
            expect(useWorkflowGenerationChatStore.getState().panelWidth).toBe(600);
        });

        it("constrains panel width to minimum (400)", () => {
            useWorkflowGenerationChatStore.getState().setPanelWidth(200);
            expect(useWorkflowGenerationChatStore.getState().panelWidth).toBe(400);
        });

        it("constrains panel width to maximum (800)", () => {
            useWorkflowGenerationChatStore.getState().setPanelWidth(1000);
            expect(useWorkflowGenerationChatStore.getState().panelWidth).toBe(800);
        });
    });

    // ===== User Messages =====
    describe("addUserMessage", () => {
        it("adds user message with generated id", () => {
            const id = useWorkflowGenerationChatStore.getState().addUserMessage("Hello");

            expect(id).toBe("uuid-1");
            const state = useWorkflowGenerationChatStore.getState();
            expect(state.messages).toHaveLength(1);
            expect(state.messages[0].role).toBe("user");
            expect(state.messages[0].content).toBe("Hello");
            expect(state.messages[0].timestamp).toBeDefined();
        });

        it("adds multiple user messages", () => {
            useWorkflowGenerationChatStore.getState().addUserMessage("First");
            useWorkflowGenerationChatStore.getState().addUserMessage("Second");

            expect(useWorkflowGenerationChatStore.getState().messages).toHaveLength(2);
        });
    });

    // ===== Assistant Messages =====
    describe("startAssistantMessage", () => {
        it("creates empty assistant message and sets streaming", () => {
            const id = useWorkflowGenerationChatStore.getState().startAssistantMessage();

            expect(id).toBe("uuid-1");
            const state = useWorkflowGenerationChatStore.getState();
            expect(state.messages).toHaveLength(1);
            expect(state.messages[0].role).toBe("assistant");
            expect(state.messages[0].content).toBe("");
            expect(state.messages[0].isResponseStreaming).toBe(true);
            expect(state.isStreaming).toBe(true);
            expect(state.currentThinkingContent).toBe("");
        });
    });

    describe("appendToThinking", () => {
        it("appends to last assistant message thinking", () => {
            useWorkflowGenerationChatStore.getState().startAssistantMessage();
            useWorkflowGenerationChatStore.getState().appendToThinking("Thinking...");
            useWorkflowGenerationChatStore.getState().appendToThinking(" more");

            const state = useWorkflowGenerationChatStore.getState();
            expect(state.messages[0].thinking).toBe("Thinking... more");
            expect(state.messages[0].isThinkingStreaming).toBe(true);
            expect(state.messages[0].thinkingExpanded).toBe(true);
            expect(state.isThinking).toBe(true);
            expect(state.currentThinkingContent).toBe("Thinking... more");
        });
    });

    describe("completeThinking", () => {
        it("completes thinking and collapses", () => {
            useWorkflowGenerationChatStore.getState().startAssistantMessage();
            useWorkflowGenerationChatStore.getState().appendToThinking("Draft");
            useWorkflowGenerationChatStore.getState().completeThinking("Final thinking");

            const state = useWorkflowGenerationChatStore.getState();
            expect(state.messages[0].thinking).toBe("Final thinking");
            expect(state.messages[0].isThinkingStreaming).toBe(false);
            expect(state.messages[0].thinkingExpanded).toBe(false);
            expect(state.isThinking).toBe(false);
        });
    });

    describe("appendToResponse", () => {
        it("appends to last assistant message content", () => {
            useWorkflowGenerationChatStore.getState().startAssistantMessage();
            useWorkflowGenerationChatStore.getState().appendToResponse("Hello");
            useWorkflowGenerationChatStore.getState().appendToResponse(" world");

            expect(useWorkflowGenerationChatStore.getState().messages[0].content).toBe(
                "Hello world"
            );
        });
    });

    describe("completeAssistantMessage", () => {
        it("completes assistant message with content", () => {
            useWorkflowGenerationChatStore.getState().startAssistantMessage();
            useWorkflowGenerationChatStore.getState().completeAssistantMessage("Final response");

            const state = useWorkflowGenerationChatStore.getState();
            expect(state.messages[0].content).toBe("Final response");
            expect(state.messages[0].isResponseStreaming).toBe(false);
            expect(state.isStreaming).toBe(false);
        });

        it("completes with thinking and plan", () => {
            const plan = createMockWorkflowPlan();

            useWorkflowGenerationChatStore.getState().startAssistantMessage();
            useWorkflowGenerationChatStore
                .getState()
                .completeAssistantMessage(
                    "Here is your workflow",
                    "I analyzed the request...",
                    plan
                );

            const state = useWorkflowGenerationChatStore.getState();
            expect(state.messages[0].thinking).toBe("I analyzed the request...");
            expect(state.messages[0].workflowPlan).toEqual(plan);
            expect(state.currentPlan).toEqual(plan);
        });
    });

    describe("setMessageError", () => {
        it("sets error on specific message", () => {
            useWorkflowGenerationChatStore.getState().addUserMessage("Test");
            const assistantId = useWorkflowGenerationChatStore.getState().startAssistantMessage();

            useWorkflowGenerationChatStore.getState().setMessageError(assistantId, "API Error");

            const state = useWorkflowGenerationChatStore.getState();
            expect(state.messages[1].content).toBe("Error: API Error");
            expect(state.messages[1].isResponseStreaming).toBe(false);
            expect(state.isStreaming).toBe(false);
        });
    });

    describe("toggleThinkingExpanded", () => {
        it("toggles thinking expanded state", () => {
            useWorkflowGenerationChatStore.getState().startAssistantMessage();
            useWorkflowGenerationChatStore.getState().appendToThinking("Some thinking");
            useWorkflowGenerationChatStore.getState().completeThinking("Final");

            const messageId = useWorkflowGenerationChatStore.getState().messages[0].id;

            // Should be collapsed after completeThinking
            expect(useWorkflowGenerationChatStore.getState().messages[0].thinkingExpanded).toBe(
                false
            );

            useWorkflowGenerationChatStore.getState().toggleThinkingExpanded(messageId);
            expect(useWorkflowGenerationChatStore.getState().messages[0].thinkingExpanded).toBe(
                true
            );

            useWorkflowGenerationChatStore.getState().toggleThinkingExpanded(messageId);
            expect(useWorkflowGenerationChatStore.getState().messages[0].thinkingExpanded).toBe(
                false
            );
        });

        it("does nothing for message without thinking", () => {
            useWorkflowGenerationChatStore.getState().addUserMessage("Test");
            const messageId = useWorkflowGenerationChatStore.getState().messages[0].id;

            useWorkflowGenerationChatStore.getState().toggleThinkingExpanded(messageId);

            expect(
                useWorkflowGenerationChatStore.getState().messages[0].thinkingExpanded
            ).toBeUndefined();
        });
    });

    // ===== Streaming State =====
    describe("streaming state", () => {
        it("sets streaming state", () => {
            useWorkflowGenerationChatStore.getState().setStreaming(true);
            expect(useWorkflowGenerationChatStore.getState().isStreaming).toBe(true);

            useWorkflowGenerationChatStore.getState().setStreaming(false);
            expect(useWorkflowGenerationChatStore.getState().isStreaming).toBe(false);
        });

        it("sets thinking state", () => {
            useWorkflowGenerationChatStore.getState().setThinking(true);
            expect(useWorkflowGenerationChatStore.getState().isThinking).toBe(true);

            useWorkflowGenerationChatStore.getState().setThinking(false);
            expect(useWorkflowGenerationChatStore.getState().isThinking).toBe(false);
        });
    });

    // ===== Connection Settings =====
    describe("connection settings", () => {
        it("sets connection with model", () => {
            useWorkflowGenerationChatStore.getState().setConnection("conn-123", "gpt-4");

            const state = useWorkflowGenerationChatStore.getState();
            expect(state.selectedConnectionId).toBe("conn-123");
            expect(state.selectedModel).toBe("gpt-4");
        });

        it("sets connection without model", () => {
            useWorkflowGenerationChatStore.getState().setConnection("conn-123");

            const state = useWorkflowGenerationChatStore.getState();
            expect(state.selectedConnectionId).toBe("conn-123");
            expect(state.selectedModel).toBeNull();
        });

        it("enables thinking", () => {
            useWorkflowGenerationChatStore.setState({ enableThinking: false });
            useWorkflowGenerationChatStore.getState().setEnableThinking(true);
            expect(useWorkflowGenerationChatStore.getState().enableThinking).toBe(true);
        });

        it("disables thinking", () => {
            useWorkflowGenerationChatStore.getState().setEnableThinking(false);
            expect(useWorkflowGenerationChatStore.getState().enableThinking).toBe(false);
        });

        it("sets thinking budget", () => {
            useWorkflowGenerationChatStore.getState().setThinkingBudget(8192);
            expect(useWorkflowGenerationChatStore.getState().thinkingBudget).toBe(8192);
        });

        it("constrains thinking budget to minimum (1024)", () => {
            useWorkflowGenerationChatStore.getState().setThinkingBudget(500);
            expect(useWorkflowGenerationChatStore.getState().thinkingBudget).toBe(1024);
        });

        it("constrains thinking budget to maximum (32768)", () => {
            useWorkflowGenerationChatStore.getState().setThinkingBudget(50000);
            expect(useWorkflowGenerationChatStore.getState().thinkingBudget).toBe(32768);
        });
    });

    // ===== Plan State =====
    describe("plan state", () => {
        it("sets plan", () => {
            const plan = createMockWorkflowPlan();

            useWorkflowGenerationChatStore.getState().setPlan(plan);

            expect(useWorkflowGenerationChatStore.getState().currentPlan).toEqual(plan);
        });

        it("clears plan with null", () => {
            useWorkflowGenerationChatStore.setState({
                currentPlan: createMockWorkflowPlan()
            });

            useWorkflowGenerationChatStore.getState().setPlan(null);

            expect(useWorkflowGenerationChatStore.getState().currentPlan).toBeNull();
        });

        it("sets creating workflow state", () => {
            useWorkflowGenerationChatStore.getState().setCreatingWorkflow(true);
            expect(useWorkflowGenerationChatStore.getState().isCreatingWorkflow).toBe(true);

            useWorkflowGenerationChatStore.getState().setCreatingWorkflow(false);
            expect(useWorkflowGenerationChatStore.getState().isCreatingWorkflow).toBe(false);
        });
    });

    // ===== Clear Chat =====
    describe("clearChat", () => {
        it("clears chat-related state", () => {
            useWorkflowGenerationChatStore.setState({
                messages: [{ id: "msg-1", role: "user", content: "Hi", timestamp: "" }],
                currentPlan: createMockWorkflowPlan(),
                currentThinkingContent: "thinking...",
                isStreaming: true,
                isThinking: true
            });

            useWorkflowGenerationChatStore.getState().clearChat();

            const state = useWorkflowGenerationChatStore.getState();
            expect(state.messages).toEqual([]);
            expect(state.currentPlan).toBeNull();
            expect(state.currentThinkingContent).toBe("");
            expect(state.isStreaming).toBe(false);
            expect(state.isThinking).toBe(false);
        });

        it("preserves panel and connection state", () => {
            useWorkflowGenerationChatStore.setState({
                isPanelOpen: true,
                panelWidth: 600,
                selectedConnectionId: "conn-123",
                messages: [{ id: "msg-1", role: "user", content: "Hi", timestamp: "" }]
            });

            useWorkflowGenerationChatStore.getState().clearChat();

            const state = useWorkflowGenerationChatStore.getState();
            expect(state.isPanelOpen).toBe(true);
            expect(state.panelWidth).toBe(600);
            expect(state.selectedConnectionId).toBe("conn-123");
        });
    });

    // ===== Reset =====
    describe("reset", () => {
        it("resets state but preserves connection settings", () => {
            useWorkflowGenerationChatStore.setState({
                isPanelOpen: true,
                panelWidth: 700,
                messages: [{ id: "msg-1", role: "user", content: "Hi", timestamp: "" }],
                isStreaming: true,
                isThinking: true,
                currentThinkingContent: "thinking...",
                selectedConnectionId: "conn-123",
                selectedModel: "gpt-4",
                currentPlan: createMockWorkflowPlan(),
                isCreatingWorkflow: true
            });

            useWorkflowGenerationChatStore.getState().reset();

            const state = useWorkflowGenerationChatStore.getState();
            expect(state.isPanelOpen).toBe(false);
            expect(state.messages).toEqual([]);
            expect(state.isStreaming).toBe(false);
            expect(state.isThinking).toBe(false);
            expect(state.currentThinkingContent).toBe("");
            expect(state.currentPlan).toBeNull();
            expect(state.isCreatingWorkflow).toBe(false);
            // Connection settings preserved
            expect(state.selectedConnectionId).toBe("conn-123");
            expect(state.selectedModel).toBe("gpt-4");
        });
    });

    // ===== Full Conversation Flow =====
    describe("full conversation flow", () => {
        it("handles complete user-assistant exchange", () => {
            // User sends message
            useWorkflowGenerationChatStore.getState().addUserMessage("Create a workflow");

            // Assistant starts responding
            useWorkflowGenerationChatStore.getState().startAssistantMessage();

            // Thinking phase
            useWorkflowGenerationChatStore.getState().appendToThinking("Analyzing request...");
            useWorkflowGenerationChatStore
                .getState()
                .appendToThinking(" Understanding requirements.");
            useWorkflowGenerationChatStore
                .getState()
                .completeThinking("Analyzed the workflow requirements.");

            // Response phase
            useWorkflowGenerationChatStore.getState().appendToResponse("I'll create ");
            useWorkflowGenerationChatStore.getState().appendToResponse("a workflow for you.");

            // Complete with plan
            const plan = createMockWorkflowPlan();
            useWorkflowGenerationChatStore
                .getState()
                .completeAssistantMessage(
                    "I'll create a workflow for you.",
                    "Analyzed the workflow requirements.",
                    plan
                );

            const state = useWorkflowGenerationChatStore.getState();
            expect(state.messages).toHaveLength(2);
            expect(state.messages[0].role).toBe("user");
            expect(state.messages[1].role).toBe("assistant");
            expect(state.messages[1].content).toBe("I'll create a workflow for you.");
            expect(state.messages[1].thinking).toBe("Analyzed the workflow requirements.");
            expect(state.messages[1].workflowPlan).toEqual(plan);
            expect(state.currentPlan).toEqual(plan);
            expect(state.isStreaming).toBe(false);
            expect(state.isThinking).toBe(false);
        });
    });
});
