/**
 * WorkflowPlanPreview Component
 *
 * Displays a preview of a proposed workflow plan generated by the AI.
 * Shows visual node cards similar to the canvas, workflow summary,
 * and provides actions to create the workflow or request refinements.
 */

import {
    BookOpen,
    Bot,
    Check,
    ChevronDown,
    ChevronRight,
    Clock,
    Code2,
    Database,
    Eye,
    FileText,
    GitBranch,
    GitFork,
    GitMerge,
    Globe,
    Hand,
    Link,
    Loader2,
    MessageSquare,
    Mic,
    Play,
    Plug,
    RefreshCw,
    Repeat,
    Send,
    Settings,
    Shuffle,
    Sparkles,
    UserCheck,
    Volume2,
    Zap
} from "lucide-react";
import { useState } from "react";
import type { WorkflowPlan, ProposedNode } from "@flowmaestro/shared";
import { cn } from "../../lib/utils";
import { Button } from "../common/Button";

interface WorkflowPlanPreviewProps {
    /** The workflow plan to preview */
    plan: WorkflowPlan;
    /** Callback to create the workflow from this plan */
    onCreateWorkflow: () => void;
    /** Callback to send refinement feedback */
    onRefine: (feedback: string) => void;
    /** Whether the workflow is currently being created */
    isCreating: boolean;
}

// Node type to icon mapping (matching canvas node icons)
const nodeIcons: Record<string, React.ElementType> = {
    // AI nodes
    llm: Bot,
    vision: Eye,
    embeddings: Sparkles,
    router: GitFork,
    "kb-query": BookOpen,
    audioInput: Mic,
    audioOutput: Volume2,
    // Input nodes
    input: Hand,
    files: FileText,
    url: Link,
    // Output nodes
    output: Send,
    templateOutput: FileText,
    action: Play,
    // Logic nodes
    conditional: GitBranch,
    switch: GitMerge,
    loop: Repeat,
    wait: Clock,
    humanReview: UserCheck,
    transform: Shuffle,
    code: Code2,
    "shared-memory": Database,
    // Utility nodes
    http: Globe,
    database: Database,
    // Integration nodes
    integration: Plug,
    fileOperations: FileText,
    // Trigger
    trigger: Zap
};

// Node type to category mapping
const nodeCategories: Record<string, string> = {
    llm: "ai",
    vision: "ai",
    embeddings: "ai",
    router: "ai",
    "kb-query": "ai",
    audioInput: "ai",
    audioOutput: "ai",
    input: "inputs",
    files: "inputs",
    url: "inputs",
    output: "outputs",
    templateOutput: "outputs",
    action: "outputs",
    conditional: "logic",
    switch: "logic",
    loop: "logic",
    wait: "logic",
    humanReview: "logic",
    transform: "logic",
    code: "logic",
    "shared-memory": "logic",
    http: "utils",
    database: "utils",
    integration: "integrations",
    fileOperations: "integrations"
};

// Category styles matching the canvas
const categoryStyles: Record<string, { border: string; iconBg: string; iconText: string }> = {
    ai: {
        border: "border-l-purple-500",
        iconBg: "bg-purple-500/20",
        iconText: "text-purple-600 dark:text-purple-400"
    },
    inputs: {
        border: "border-l-green-500",
        iconBg: "bg-green-500/20",
        iconText: "text-green-600 dark:text-green-400"
    },
    outputs: {
        border: "border-l-blue-500",
        iconBg: "bg-blue-500/20",
        iconText: "text-blue-600 dark:text-blue-400"
    },
    logic: {
        border: "border-l-orange-500",
        iconBg: "bg-orange-500/20",
        iconText: "text-orange-600 dark:text-orange-400"
    },
    utils: {
        border: "border-l-cyan-500",
        iconBg: "bg-cyan-500/20",
        iconText: "text-cyan-600 dark:text-cyan-400"
    },
    integrations: {
        border: "border-l-pink-500",
        iconBg: "bg-pink-500/20",
        iconText: "text-pink-600 dark:text-pink-400"
    }
};

// Mini node card component
function MiniNodeCard({ node, index }: { node: ProposedNode; index: number }) {
    const Icon = nodeIcons[node.type] || Settings;
    const category = nodeCategories[node.type] || "utils";
    const styles = categoryStyles[category] || categoryStyles.utils;

    return (
        <div
            className={cn(
                "flex items-center gap-2 px-2.5 py-2 rounded-lg",
                "bg-card border border-border",
                "border-l-[3px]",
                styles.border
            )}
        >
            {/* Step number */}
            <span className="text-[10px] text-muted-foreground/60 font-medium w-4">
                {index + 1}
            </span>

            {/* Icon */}
            <div className={cn("p-1 rounded", styles.iconBg)}>
                <Icon className={cn("w-3 h-3", styles.iconText)} />
            </div>

            {/* Label and type */}
            <div className="flex-1 min-w-0">
                <div className="text-xs font-medium text-foreground truncate">{node.label}</div>
                <div className="text-[10px] text-muted-foreground font-mono">{node.type}</div>
            </div>
        </div>
    );
}

export function WorkflowPlanPreview({
    plan,
    onCreateWorkflow,
    onRefine,
    isCreating
}: WorkflowPlanPreviewProps) {
    const [showRefineInput, setShowRefineInput] = useState(false);
    const [refineFeedback, setRefineFeedback] = useState("");
    const [showJson, setShowJson] = useState(false);

    const handleRefineSubmit = () => {
        if (refineFeedback.trim()) {
            onRefine(refineFeedback.trim());
            setRefineFeedback("");
            setShowRefineInput(false);
        }
    };

    const handleKeyPress = (e: React.KeyboardEvent) => {
        if (e.key === "Enter" && !e.shiftKey) {
            e.preventDefault();
            handleRefineSubmit();
        }
        if (e.key === "Escape") {
            setShowRefineInput(false);
            setRefineFeedback("");
        }
    };

    const totalNodes = plan.nodes.length;
    const totalEdges = plan.edges.length;

    return (
        <div className="mt-3 border rounded-lg overflow-hidden bg-card">
            {/* Header */}
            <div className="px-4 py-3 bg-primary/5 border-b border-border">
                <div className="flex items-center gap-2">
                    <Sparkles className="w-4 h-4 text-primary" />
                    <h4 className="font-semibold text-sm">{plan.name}</h4>
                </div>
                {plan.description && (
                    <p className="text-xs text-muted-foreground mt-1">{plan.description}</p>
                )}
            </div>

            {/* Summary */}
            {plan.summary && (
                <div className="px-4 py-3 border-b border-border">
                    <p className="text-sm text-foreground leading-relaxed">{plan.summary}</p>
                </div>
            )}

            {/* Visual Node Preview */}
            <div className="px-4 py-3 border-b border-border">
                <div className="flex items-center justify-between mb-3">
                    <span className="text-xs font-medium text-muted-foreground uppercase tracking-wide">
                        Workflow Nodes
                    </span>
                    <span className="text-xs text-muted-foreground">
                        {totalNodes} nodes • {totalEdges} connections
                    </span>
                </div>

                {/* Node cards in a flow */}
                <div className="space-y-2">
                    {plan.nodes.map((node, index) => (
                        <div key={node.id} className="relative">
                            <MiniNodeCard node={node} index={index} />
                            {/* Connector line */}
                            {index < plan.nodes.length - 1 && (
                                <div className="absolute left-[22px] top-full w-[2px] h-2 bg-border" />
                            )}
                        </div>
                    ))}
                </div>
            </div>

            {/* Collapsible JSON View */}
            <div className="border-b border-border">
                <button
                    onClick={() => setShowJson(!showJson)}
                    className={cn(
                        "flex items-center gap-2 w-full px-4 py-2",
                        "text-xs font-medium text-muted-foreground",
                        "hover:bg-muted/30 transition-colors"
                    )}
                >
                    {showJson ? (
                        <ChevronDown className="w-3.5 h-3.5" />
                    ) : (
                        <ChevronRight className="w-3.5 h-3.5" />
                    )}
                    <Code2 className="w-3.5 h-3.5" />
                    <span>View JSON Definition</span>
                </button>
                {showJson && (
                    <div className="px-4 pb-3">
                        <pre
                            className={cn(
                                "p-3 rounded-lg text-xs font-mono",
                                "bg-muted/50 border border-border",
                                "overflow-x-auto max-h-64 overflow-y-auto",
                                "text-foreground"
                            )}
                        >
                            {JSON.stringify(plan, null, 2)}
                        </pre>
                    </div>
                )}
            </div>

            {/* Actions */}
            <div className="px-4 py-3">
                {!showRefineInput ? (
                    <div className="flex gap-2">
                        <Button
                            onClick={onCreateWorkflow}
                            disabled={isCreating}
                            className={cn(
                                "flex-1 gap-2",
                                "bg-primary text-primary-foreground",
                                "hover:bg-primary/90"
                            )}
                        >
                            {isCreating ? (
                                <>
                                    <Loader2 className="w-4 h-4 animate-spin" />
                                    Creating...
                                </>
                            ) : (
                                <>
                                    <Check className="w-4 h-4" />
                                    Create Workflow
                                </>
                            )}
                        </Button>
                        <Button
                            onClick={() => setShowRefineInput(true)}
                            disabled={isCreating}
                            variant="secondary"
                            className="gap-2"
                        >
                            <RefreshCw className="w-4 h-4" />
                            Refine
                        </Button>
                    </div>
                ) : (
                    <div className="space-y-2">
                        <div className="flex items-center gap-2 text-xs text-muted-foreground">
                            <MessageSquare className="w-3.5 h-3.5" />
                            <span>What would you like to change?</span>
                        </div>
                        <div className="flex gap-2">
                            <input
                                type="text"
                                value={refineFeedback}
                                onChange={(e) => setRefineFeedback(e.target.value)}
                                onKeyDown={handleKeyPress}
                                placeholder="e.g., Add error handling, use a different node..."
                                className={cn(
                                    "flex-1 px-3 py-2 rounded-lg text-sm",
                                    "bg-muted border border-border",
                                    "text-foreground placeholder:text-muted-foreground",
                                    "focus:outline-none focus:ring-2 focus:ring-primary"
                                )}
                                autoFocus
                            />
                            <Button
                                onClick={handleRefineSubmit}
                                disabled={!refineFeedback.trim()}
                                size="sm"
                            >
                                Send
                            </Button>
                            <Button
                                onClick={() => {
                                    setShowRefineInput(false);
                                    setRefineFeedback("");
                                }}
                                variant="ghost"
                                size="sm"
                            >
                                Cancel
                            </Button>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
}
