import { Copy, ExternalLink } from "lucide-react";
import { useState, useEffect } from "react";
import { FormField, FormSection } from "../../../components/common/FormField";
import { Input } from "../../../components/common/Input";
import { Select } from "../../../components/common/Select";
import { Textarea } from "../../../components/common/Textarea";

interface TriggerNodeConfigProps {
    data: Record<string, unknown>;
    onUpdate: (config: unknown) => void;
}

const triggerTypes = [
    { value: "manual", label: "Manual" },
    { value: "schedule", label: "Schedule (Cron)" },
    { value: "webhook", label: "Webhook" },
    { value: "event", label: "Event" }
];

const cronPresets = [
    { value: "custom", label: "Custom" },
    { value: "0 * * * *", label: "Every hour" },
    { value: "0 0 * * *", label: "Every day at midnight" },
    { value: "0 9 * * 1-5", label: "Weekdays at 9am" },
    { value: "0 0 * * 0", label: "Every Sunday at midnight" },
    { value: "0 0 1 * *", label: "First day of month" }
];

const webhookMethods = [
    { value: "POST", label: "POST" },
    { value: "GET", label: "GET" },
    { value: "PUT", label: "PUT" },
    { value: "DELETE", label: "DELETE" },
    { value: "ANY", label: "ANY" }
];

const authTypes = [
    { value: "none", label: "None" },
    { value: "api_key", label: "API Key" },
    { value: "hmac", label: "HMAC Signature" },
    { value: "bearer", label: "Bearer Token" }
];

const timezones = [
    { value: "UTC", label: "UTC" },
    { value: "America/New_York", label: "Eastern Time (US)" },
    { value: "America/Chicago", label: "Central Time (US)" },
    { value: "America/Denver", label: "Mountain Time (US)" },
    { value: "America/Los_Angeles", label: "Pacific Time (US)" },
    { value: "Europe/London", label: "London" },
    { value: "Europe/Paris", label: "Paris" },
    { value: "Asia/Tokyo", label: "Tokyo" },
    { value: "Asia/Shanghai", label: "Shanghai" },
    { value: "Australia/Sydney", label: "Sydney" }
];

export function TriggerNodeConfig({ data, onUpdate }: TriggerNodeConfigProps) {
    const [triggerType, setTriggerType] = useState((data.triggerType as string) || "manual");
    const [enabled, setEnabled] = useState((data.enabled as boolean) ?? true);

    // Schedule config
    const [cronExpression, setCronExpression] = useState((data.cronExpression as string) || "");
    const [timezone, setTimezone] = useState((data.timezone as string) || "UTC");
    const [cronPreset, setCronPreset] = useState("custom");

    // Webhook config
    const [webhookMethod, setWebhookMethod] = useState((data.webhookMethod as string) || "POST");
    const [authType, setAuthType] = useState((data.authType as string) || "none");
    // webhookUrl is read-only, generated by backend when workflow is saved
    const webhookUrl = (data.webhookUrl as string) || "";

    // Manual config
    const [description, setDescription] = useState((data.description as string) || "");
    const [inputSchema, setInputSchema] = useState((data.inputSchema as string) || "");

    useEffect(() => {
        const config: Record<string, unknown> = {
            triggerType,
            enabled
        };

        if (triggerType === "schedule") {
            config.cronExpression = cronExpression;
            config.timezone = timezone;
        } else if (triggerType === "webhook") {
            config.webhookMethod = webhookMethod;
            config.authType = authType;
            if (webhookUrl) config.webhookUrl = webhookUrl;
        } else if (triggerType === "manual") {
            if (description) config.description = description;
            if (inputSchema) {
                try {
                    config.inputSchema = JSON.parse(inputSchema);
                } catch {
                    // Keep as string if invalid JSON
                    config.inputSchema = inputSchema;
                }
            }
        }

        onUpdate(config);
    }, [
        triggerType,
        enabled,
        cronExpression,
        timezone,
        webhookMethod,
        authType,
        description,
        inputSchema
    ]);

    const handleCronPresetChange = (value: string) => {
        setCronPreset(value);
        if (value !== "custom") {
            setCronExpression(value);
        }
    };

    const copyWebhookUrl = () => {
        if (webhookUrl) {
            navigator.clipboard.writeText(webhookUrl);
        }
    };

    return (
        <div>
            <FormSection title="Trigger Configuration">
                <FormField label="Trigger Type" description="How this workflow is started">
                    <Select value={triggerType} onChange={setTriggerType} options={triggerTypes} />
                </FormField>

                <FormField label="Enable Trigger">
                    <label className="flex items-center gap-2 cursor-pointer">
                        <Input
                            type="checkbox"
                            checked={enabled}
                            onChange={(e) => setEnabled(e.target.checked)}
                            className="w-4 h-4 rounded border-border text-primary focus:ring-2 focus:ring-primary/20"
                        />
                        <span className="text-sm">
                            {enabled ? "Trigger is active" : "Trigger is disabled"}
                        </span>
                    </label>
                </FormField>
            </FormSection>

            {triggerType === "schedule" && (
                <FormSection title="Schedule Settings">
                    <FormField label="Preset">
                        <Select
                            value={cronPreset}
                            onChange={handleCronPresetChange}
                            options={cronPresets}
                        />
                    </FormField>

                    <FormField
                        label="Cron Expression"
                        description="Standard cron format: minute hour day month weekday"
                    >
                        <Input
                            type="text"
                            value={cronExpression}
                            onChange={(e) => {
                                setCronExpression(e.target.value);
                                setCronPreset("custom");
                            }}
                            placeholder="0 9 * * 1-5"
                            className="font-mono"
                        />
                    </FormField>

                    <FormField label="Timezone">
                        <Select value={timezone} onChange={setTimezone} options={timezones} />
                    </FormField>

                    {cronExpression && (
                        <div className="p-3 bg-muted/50 rounded-lg border border-border">
                            <p className="text-xs text-muted-foreground">
                                Preview: Next runs will be calculated when saved
                            </p>
                        </div>
                    )}
                </FormSection>
            )}

            {triggerType === "webhook" && (
                <FormSection title="Webhook Settings">
                    <FormField label="HTTP Method">
                        <Select
                            value={webhookMethod}
                            onChange={setWebhookMethod}
                            options={webhookMethods}
                        />
                    </FormField>

                    <FormField label="Authentication">
                        <Select value={authType} onChange={setAuthType} options={authTypes} />
                    </FormField>

                    {webhookUrl ? (
                        <FormField label="Webhook URL">
                            <div className="flex gap-2">
                                <Input
                                    type="text"
                                    value={webhookUrl}
                                    readOnly
                                    className="font-mono text-xs flex-1"
                                />
                                <button
                                    onClick={copyWebhookUrl}
                                    className="p-2 hover:bg-muted rounded transition-colors"
                                    title="Copy URL"
                                >
                                    <Copy className="w-4 h-4" />
                                </button>
                                <a
                                    href={webhookUrl}
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="p-2 hover:bg-muted rounded transition-colors"
                                    title="Open URL"
                                >
                                    <ExternalLink className="w-4 h-4" />
                                </a>
                            </div>
                        </FormField>
                    ) : (
                        <div className="p-3 bg-muted/50 rounded-lg border border-border">
                            <p className="text-xs text-muted-foreground">
                                Webhook URL will be generated when the workflow is saved
                            </p>
                        </div>
                    )}
                </FormSection>
            )}

            {triggerType === "manual" && (
                <FormSection title="Manual Trigger Settings">
                    <FormField
                        label="Description"
                        description="Help text shown when triggering manually"
                    >
                        <Textarea
                            value={description}
                            onChange={(e) => setDescription(e.target.value)}
                            placeholder="Describe what this workflow does..."
                            rows={2}
                        />
                    </FormField>

                    <FormField
                        label="Input Schema (JSON)"
                        description="Optional JSON schema for required inputs"
                    >
                        <Textarea
                            value={inputSchema}
                            onChange={(e) => setInputSchema(e.target.value)}
                            placeholder='{ "type": "object", "properties": { ... } }'
                            rows={4}
                            className="font-mono text-xs"
                        />
                    </FormField>
                </FormSection>
            )}

            {triggerType === "event" && (
                <FormSection title="Event Settings">
                    <div className="p-3 bg-muted/50 rounded-lg border border-border">
                        <p className="text-xs text-muted-foreground">
                            Event triggers are configured through external integrations. Select
                            integration webhooks to trigger this workflow.
                        </p>
                    </div>
                </FormSection>
            )}
        </div>
    );
}
